services:
  miss_idisplay:
    container_name: miss_idisplay
    image: miss_idisplay:v1
    command: bash
    ports:
      - "8181:8181"
    privileged: true 
    network_mode: "host"
    volumes: 
      - ../:/idisplay_ws